### Get VAPID_PUBLIC_KEY

GET http://localhost:8080/subscription HTTP/1.1

### Subscribe a client

POST http://localhost:8080/subscription HTTP/1.1
content-type: application/json

{
    "endpoint":"https://updates.push.services.mozilla.com/wpush/v2/gAAAAABnKN2_5id0ZFYI5BJjRcz-Ly3JCY7ZhngcrwBxgIs-n_6UCaspQ5oeI2Qq2ULeSFXK5lO4gE8aKGGu7zrWBZJwDlosZDCtRGvGdj79-jBVYNKYczIjXgB4XWrr8Lt_3Pqeoy00JjimWZrW6jpkpw0cFKiOMagBqag3O0WQPFKW6fcIXoA",
    "expirationTime":null,
    "keys":{
        "auth":"A5SQrEo9dzbnUeDvgdR1ZQ",
        "p256dh":"BBMIyKM6OnkH0TOYZl3ghn3xRv-h8w13vTpN1rG21KYw1zw4PsFhWsCMf55Or_j31WQlbmVNfA_-1JaTgr1ghhw"
        }
}

### Send Push Notification

POST http://localhost:8080/push_message HTTP/1.1
content-type: application/json

{
    "title": "Eruzione vulcanica in Indonesia: ci sono diversi morti e migliaia di sfollati",
    "options": {
        "body": "Eruzione del vulcano Lewotobi Laki Laki: 10 morti e migliaia di sfollati a Flores, Indonesia.", 
        "icon": "/static/images/icon.png",
        "badge": "/static/images/badge.png",
        "image": "https://www.scienzenotizie.it/wp-content/uploads/2024/11/tangled-earbud-cable-m.jpg", 
        "data": {
            "url": "https://www.scienzenotizie.it/2024/11/04/eruzione-vulcanica-in-indonesia-ci-sono-diversi-morti-e-migliaia-di-sfollati-4496324"
            },
        "tag": "eruzione-vulcanica-in-indonesia-ci-sono-diversi-morti-e-migliaia-di-sfollati-4496324"
    }
}
